export default[
    {
        id:1,
        sr:"../imgs/new1.jpg" ,
        heading:"Maybelline Fit Me Foundation",
        des:"Matte + Poreless Liquid",
        rating:"4.5",
        review:"8267",
        off:"30% off",
        rate:"Rs. 415",
        price:"599",
        offer:"Buy 3 items, save extra 5%",

    },
    {
        id:2,
        sr:"../imgs/new3.jpg" ,
        heading:"Pamper ",
        des:"Diaper Pants-XL, 112 Pieces",
        rating:"4.6",
        review:"2267",
        off:"23% off",
        rate:"Rs. 1,629",
        price:"2,142",
        offer:"Buy 3 items, save extra 5%",

   
    },
    {
        id:3,
        sr:"../imgs/new2.jpg", 
        heading:"Whisper Ultra Clean",
        des:" XL+ Sanitary Pad, Pack of 50 ",
        rating:"4.1",
        review:"5267",
        off:"34% off",
        rate:"Rs. 340",
        price:"520",
        offer:"Buy 3 items, save extra 5%",
    },
    {
        id:4,
        sr:"../imgs/new4.jpg" ,
        heading:"Surgeo Disposal Mask",
        des:"Surgical Mask Pack Of 3 Ply",
        rating:"4.1",
        review:"5267",
        off:"88% off",
        rate:"Rs. 223",
        price:"1,998",
        offer:"Bank Offer",

    },
    {
        id:5,
        sr:"../imgs/new5.jpg" ,
        heading:"Ecovani Anti-Chafing Cream",
        des:"for Rashes & Itching 100 ml",
        rating:"4.1",
        review:"5267",
        off:"15% off",
        rate:"Rs. 279",
        price:"325",
        offer:"Buy 2 items, save extra 5%",

    },
    {
        id:6,
        sr:"../imgs/new6.jpg" ,
        heading:"Sri Sri Tattva Body Butter",
        des:"For both Men & Women (150 g)",
        rating:"4.1",
        review:"5267",
        off:"20% off",
        rate:"Rs. 235",
        price:"250",
        offer:"Buy 3 items, save extra 5%",

    },
    {
        id:7,
        sr:"../imgs/new7.jpg" ,
        heading:"BEARDO Beard Wash",
        des:"For Men 200 ml",
        rating:"4.1",
        review:"5267",
        off:"30% off",
        rate:"Rs. 350",
        price:"500",
        offer:"Buy 1 items, save extra 5%",
    },
]